version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:obama2001@mysql/time-cutter
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: time-cutter
      MYSQL_USER: root
      MYSQL_PASSWORD: obama2001
      MYSQL_ROOT_PASSWORD: obama2001
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: